# -*- coding: utf-8 -*-
"""stage_0_Prem.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SmI-QPYZfR-Eg7Uq5y4M5E6xFws4Mzv1
"""

name = "Prem Thapa"
email = "premthapa2580@gmail.com"
slack_username = "@Prem"
biostack = "Drug Discovery"


print(name)
print(email)
print(slack_username)
print(biostack)