# -*- coding: utf-8 -*-
"""Stage_0_Yissa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNVOD0ayo3qeQN2y9kwEbkKiVBZiqhCR
"""

Name  = "Toheeb Damilola "
gmail = "toheebyissa@gmail.com"
Slack_name = "@Toheeb "
biostack = "drug discovery"

print(Name)
print(gmail)
print(Slack_name)
print(biostack)